<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<link rel="stylesheet" href="css/uikit.css">
</head>
<body>
	

		<!--<ul class="uk-nav uk-nav-navbar">
		  <li class="uk-nav-header">Filter:</li>
		  <li data-uk-filter="" class="uk-active"><a href="#">ALL</a></li>
		  <li data-uk-filter="blue"><a href="#">BLUE</a></li>
		  <li data-uk-filter="green"><a href="#">GREEN</a></li>
		  <li class="uk-nav-divider"></li>
		</ul>
		<ul class="uk-nav uk-nav-navbar">
		  <li class="uk-nav-header">Sort:</li>
		  <li data-uk-sort="numbers">
		    <a href="#">NUMBERS <i class="uk-icon-sort-numeric-asc"></i></a>
		  </li>
		  <li data-uk-sort="numbers:desc">
		    <a href="#">NUMBERS <i class="uk-icon-sort-numeric-desc"></i>
		  </a></li>
		  <li data-uk-sort="letters">
		    <a href="#">LETTERS <i class="uk-icon-sort-alpha-asc"></i></a>
		  </li>
		  <li data-uk-sort="letters:desc">
		    <a href="#">LETTERS <i class="uk-icon-sort-alpha-desc"></i></a>
		  </li>
		</ul>-->

	<!-- Menú de navegación -->
	<nav class="uk-navbar" data-uk-tab>
		<ul class="uk-navbar-nav">
			<li class="uk-parent"><a href="">Registrate</a></li>
			<li class="uk-parent"><a href="">Inicia sesión</a></li>
		</ul>
	</nav>
	<!-- Fin menú de navegación -->

	
	<div class="uk-container uk-container-center uk-margin-large-top">
		<div class="uk-grid">
			<?php echo $nombre; ?>
		</div>
	</div>
</body>
</html>
<script src="js/jquery.js"></script>
<script src="js/funciones.js"></script>
<script src="js/uikit.js"></script>